import Navbar from '@/components/navbar'
import './globals.css'
import FooterComponent from '@/components/footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='mx-auto'>
        <Navbar />
        {children}
        <FooterComponent />
        </body>
    </html>
  )
}
